### ISSUE TITLE
Views in multi-device applications are not supported

### ISSUE THREAD

**Issue by dvpublic** [yktoo/dklang#16]
Firemonkey allows to add views to multi-device projects
http://docwiki.embarcadero.com/RADStudio/XE8/en/Adding_Views_to_Your_Multi-Device_Project

If you add view for a form then additional directive will appear in the code:

  ```
TMyForm = class(TForm)
   ....
  end;

  implementation
  {$R *.fmx}
  {$R *.LgXhdpiTb.fmx ANDROID}    // view
```

After that the form won't be translated if added view is in use.

The problem is in incorrect `Controller.ActualSectionName`. It has value  `MyForm_LgXhdpiTb`
insted of  `MyForm`. As result, follow code 
  `Translations.FindComponentName(Controller.ActualSectionName);`
in function
  `TDKLanguageManager.ApplyTranToController`
returns nil... and translation is not made.

**Comment by bjmillerpa** [comment]
That is because Firemonkey is renaming the form in the new view's .fmx file. A work around, for now, would be to assign the SectionName property of the controller in the form editor so that the controller always looks for the same name, even if the form has been renamed. There is also the issue that you might WANT the name to change this way if you are making a lot of changes in the view, so that the view has its own section in the translations. Not sure of a non-kludgy way of dealing with this, but will try.

**Comment by bjmillerpa** [comment]
Wrote a work around that tests and iterates through possible section names by stripping the final characters off starting with the final underscore.
